# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sendika_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SendikaEkle(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(429, 334)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 60, 271, 214))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(30, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sendikaAdiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sendikaAdiLineEdit.setObjectName("sendikaAdiLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sendikaAdiLineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sendikaKoduLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sendikaKoduLineEdit.setObjectName("sendikaKoduLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sendikaKoduLineEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sendikaBaskaniLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sendikaBaskaniLineEdit.setObjectName("sendikaBaskaniLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sendikaBaskaniLineEdit)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.kurulusTarihiDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.kurulusTarihiDateEdit.setObjectName("kurulusTarihiDateEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.kurulusTarihiDateEdit)
        self.iptalButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.iptalButton.setObjectName("iptalButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.iptalButton)
        self.kaydetButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.kaydetButton.setObjectName("kaydetButton")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.kaydetButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sendika Ekle"))
        self.label.setText(_translate("Dialog", "Sendika Adı"))
        self.label_2.setText(_translate("Dialog", "Sendika Kodu"))
        self.label_3.setText(_translate("Dialog", "Sendika Başkanı"))
        self.label_4.setText(_translate("Dialog", "Kuruluş Tarihi"))
        self.iptalButton.setText(_translate("Dialog", "İptal"))
        self.kaydetButton.setText(_translate("Dialog", "Kaydet"))
