# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sendika_takip.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 412)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(60, 70, 641, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(60, 250, 641, 86))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sendikaAdiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.sendikaAdiLineEdit.setObjectName("sendikaAdiLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sendikaAdiLineEdit)
        self.araButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.araButton.setObjectName("araButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.araButton)
        self.silButton = QtWidgets.QPushButton(self.formLayoutWidget)
        self.silButton.setObjectName("silButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.silButton)
        self.ekleButton = QtWidgets.QPushButton(self.centralwidget)
        self.ekleButton.setGeometry(QtCore.QRect(60, 40, 91, 23))
        self.ekleButton.setObjectName("ekleButton")
        self.yenileButton = QtWidgets.QPushButton(self.centralwidget)
        self.yenileButton.setGeometry(QtCore.QRect(610, 40, 91, 23))
        self.yenileButton.setObjectName("yenileButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sendika Takip Programı"))
        self.label.setText(_translate("MainWindow", "Sendika Adı"))
        self.araButton.setText(_translate("MainWindow", "Ara"))
        self.silButton.setText(_translate("MainWindow", "Sil"))
        self.ekleButton.setText(_translate("MainWindow", "Sendika Ekle"))
        self.yenileButton.setText(_translate("MainWindow", "Tabloyu Yenile"))
