# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uye_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UyeEkle(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(367, 198)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(40, 40, 281, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(50, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.uyeAdiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uyeAdiLineEdit.setObjectName("uyeAdiLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uyeAdiLineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.uyeYasiSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.uyeYasiSpinBox.setMaximum(120)
        self.uyeYasiSpinBox.setObjectName("uyeYasiSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uyeYasiSpinBox)
        self.uyeMeslegiLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.uyeMeslegiLineEdit.setObjectName("uyeMeslegiLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uyeMeslegiLineEdit)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.kaydetButton = QtWidgets.QPushButton(Dialog)
        self.kaydetButton.setGeometry(QtCore.QRect(250, 140, 75, 23))
        self.kaydetButton.setObjectName("kaydetButton")
        self.iptalButton = QtWidgets.QPushButton(Dialog)
        self.iptalButton.setGeometry(QtCore.QRect(160, 140, 75, 23))
        self.iptalButton.setObjectName("iptalButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Üye Ekle"))
        self.label.setText(_translate("Dialog", "Üye Adı"))
        self.label_2.setText(_translate("Dialog", "Üye Yaşı"))
        self.label_3.setText(_translate("Dialog", "Üye Mesleği"))
        self.kaydetButton.setText(_translate("Dialog", "Kaydet"))
        self.iptalButton.setText(_translate("Dialog", "İptal"))
